channels:
- conda-forge
dependencies:
- python=3.12.5
- pip<=25.2
- pip:
  - mlflow==3.1.4
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - lightgbm==4.6.0
  - matplotlib==3.10.3
  - numpy==2.3.2
  - pandas==2.3.1
  - psutil==7.0.0
  - pyarrow==20.0.0
  - scikit-learn==1.7.1
  - scipy==1.16.1
name: mlflow-env
